from enum import Enum


class WSEventType(str, Enum):
    # Client -> Server Events
    JOIN_ROOM = "JOIN_ROOM"
    ANSWER_SUBMITTED = "ANSWER_SUBMITTED"
    HEARTBEAT = "HEARTBEAT"
    LEAVE_ROOM = "LEAVE_ROOM"

    # Server -> Client Events
    QUESTION_DELIVERED = "QUESTION_DELIVERED"
    ANSWER_RECEIVED = "ANSWER_RECEIVED"
    INTERVIEW_STARTED = "INTERVIEW_STARTED"
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED"
    PARTICIPANT_JOINED = "PARTICIPANT_JOINED"
    PARTICIPANT_LEFT = "PARTICIPANT_LEFT"
    ERROR = "ERROR"
    PONG = "PONG"
